version: 0.2 
phases: 
  pre_build: 
    commands: 
      - echo "Starting a build..."
  build: 
    commands: 
      - npm run test:ci
      - npm run build 
  post_build: 
    commands: 
      - echo "All done!"
cache: 
  paths: 
    - 'node_modules/**/*' 
